apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
  labels:
    purpose: "node-affinity-demo"
spec:
  affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions: #it will match with this labels
        - key: hardware
          operator: In
          values:
          - gpu
  containers:
  - name: nginx
    image: nginx
  tolerations: #matched
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"