apiVersion: v1
kind: Pod
metadata:
  name: antinode-affinity
  labels:
    purpose: "antinode-affinity-demo"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions: #it will match with this labels
          - key: hardware
            operator: NotIn
            values:
            - gpu
  containers:
  - name: nginx
    image: nginx
  tolerations: #matched
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"